# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:21.0.0
  amd64: ghcr.io/hassio-addons/base:21.0.0

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CarConnectivity"
  org.opencontainers.image.description: "Addon version of Carconnectivity made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
  org.opencontainers.image.source: "https://github.com/marcantoinet/carconnectivity-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  AUDI_VERSION: "v0.3.2"
  SEAT_VERSION: "v0.6.3"
  SKODA_VERSION: "v0.12.5"
  VW_VERSION: "v0.10.5"
  VWNA_VERSION: "v0.1.21"
  RENAULTDACIA_VERSION: "v0.1a1"
  TRONITY_VERSION: "v0.7.2"
  VOLVO_VERSION: "v0.1a2"
  ABRP_VERSION: "v0.8.2"
  MQTT_VERSION: "v0.10.4"
  MQTTHA_VERSION: "v0.6.5"
  WEBUI_VERSION: "v0.7.2"
  CC_VERSION: "v0.11.9"
